export enum Pericia {
  Acrobacia = 'Acrobacia',
  Adestramento = 'Adestramento',
  Atletismo = 'Atletismo',
  Atuacao = 'Atuação',
  Cavalgar = 'Cavalgar',
  Conhecimento = 'Conhecimento',
  Cura = 'Cura',
  Diplomacia = 'Diplomacia',
  Enganacao = 'Enganação',
  Fortitude = 'Fortitude',
  Furtividade = 'Furtividade',
  Guerra = 'Guerra',
  Iniciativa = 'Iniciativa',
  Intimidacao = 'Intimidação',
  Intuicao = 'Intuição',
  Investigacao = 'Investigação',
  Jogatina = 'Jogatina',
  Ladinagem = 'Ladinagem',
  Luta = 'Luta',
  Misticismo = 'Misticismo',
  Nobreza = 'Nobreza',
  Ofício = 'Ofício',
  Percepcao = 'Percepção',
  Pilotagem = 'Pilotagem',
  Pontaria = 'Pontaria',
  Reflexos = 'Reflexos',
  Religiao = 'Religião',
  Sobrevivencia = 'Sobrevivência',
  Vontade = 'Vontade'
}

export enum Atributo {
  For = 'Força',
  Des = 'Destreza',
  Con = 'Constituição',
  Int = 'Inteligência',
  Sab = 'Sabedoria',
  Car = 'Carisma'
}
